### PR TITLE
fix(variableEvent): changing from variableEvent tovVariableEvents pro…

### PR DESCRIPTION
**Pull request by prithviraj-maurya**
fixes #355 #388

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Thanks! Please update your commit message to fit our guidelines

```text
fix(camunda): rename to variableEvents

Related to bpmn-io/bpmn-js-properties-panel#355
```

after this, we're fine 🚀

**Review by pinussilvestrus — CHANGES_REQUESTED** [review]
Thanks! Please update your commit message to fit our guidelines

```text
fix(camunda): rename to variableEvents

Related to bpmn-io/bpmn-js-properties-panel#355
```

after this, we're fine 🚀

**Comment by prithviraj-maurya** [comment]
Is it fine now ??

**Comment by pinussilvestrus** [comment]
We want to have one single commit fixing the issue to keep the commit history clean. Therefore it would be great to squash all 3 commits in this PR together to a single one with the commit message I proposed.

**Comment by pinussilvestrus** [comment]
I merged it via cd4a417c1ee7831646f896d2360854aee7ee1ad3, thanks a lot !

**Comment by prithviraj-maurya** [comment]
Can we close updatream PR as well ?
https://github.com/bpmn-io/bpmn-js-properties-panel/pull/388

**Comment by pinussilvestrus** [comment]
I am on it. I have to release the moddle lib and integrate it properly.

**Comment by prithviraj-maurya** [comment]
Sure do let me know thank you.

**Pull request closed without merging**
